"""Deterministic coordination support for managed-session Hunter scans."""

from __future__ import annotations

__version__ = "1.0.0"

SUCCESS = 0
OPERATIONAL_ERROR = 1
SCHEMA_OR_VERIFICATION_FAILURE = 2
INCOMPLETE_COVERAGE = 3
MISSING_VALIDATION = 4
TARGET_REPOSITORY_MODIFIED = 5

DEFAULT_PARENT_ACU = 10
DEFAULT_INVESTIGATOR_ACU = 5
DEFAULT_COVERAGE_AUDITOR_ACU = 5
DEFAULT_VALIDATOR_ACU = 7
DEFAULT_CRITIC_ACU = 5
DEFAULT_MAX_INVESTIGATION_CHILDREN = 7
DEFAULT_MAX_VALIDATION_CHILDREN = 5
DEFAULT_MAX_RETRIES = 2
DEFAULT_MAXIMUM_TOTAL_ACU = 55
